src/main/java/com/ga2w20/entities/Client.java
package com.ga2w20.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Client entity
 *
 * @author Svitlana Myronova
 */
@Entity
@Table(name = "client", catalog = "ga2w20", schema = "")
@NamedQueries({
    @NamedQuery(name = "Client.findAll", query = "SELECT c FROM Client c"),
    @NamedQuery(name = "Client.findById", query = "SELECT c FROM Client c WHERE c.id = :id"),
    @NamedQuery(name = "Client.findByTitle", query = "SELECT c FROM Client c WHERE c.title = :title"),
    @NamedQuery(name = "Client.findByLastName", query = "SELECT c FROM Client c WHERE c.lastName = :lastName"),
    @NamedQuery(name = "Client.findByFirstName", query = "SELECT c FROM Client c WHERE c.firstName = :firstName"),
    @NamedQuery(name = "Client.findByAddress1", query = "SELECT c FROM Client c WHERE c.address1 = :address1"),
    @NamedQuery(name = "Client.findByAddress2", query = "SELECT c FROM Client c WHERE c.address2 = :address2"),
    @NamedQuery(name = "Client.findByCity", query = "SELECT c FROM Client c WHERE c.city = :city"),
    @NamedQuery(name = "Client.findByCountry", query = "SELECT c FROM Client c WHERE c.country = :country"),
    @NamedQuery(name = "Client.findByPostalCode", query = "SELECT c FROM Client c WHERE c.postalCode = :postalCode"),
    @NamedQuery(name = "Client.findByHomeTelephone", query = "SELECT c FROM Client c WHERE c.homeTelephone = :homeTelephone"),
    @NamedQuery(name = "Client.findByCompanyName", query = "SELECT c FROM Client c WHERE c.companyName = :companyName"),
    @NamedQuery(name = "Client.findByCellTelephone", query = "SELECT c FROM Client c WHERE c.cellTelephone = :cellTelephone"),
    @NamedQuery(name = "Client.findByEmail", query = "SELECT c FROM Client c WHERE c.email = :email"),
    @NamedQuery(name = "Client.findByPassword", query = "SELECT c FROM Client c WHERE c.password = :password"),
    @NamedQuery(name = "Client.findBySalt", query = "SELECT c FROM Client c WHERE c.salt = :salt"),
    @NamedQuery(name = "Client.findByManager", query = "SELECT c FROM Client c WHERE c.manager = :manager")})
public class Client implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Size(max = 45)
    @Column(name = "title")
    private String title;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "lastName")
    private String lastName;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "firstName")
    private String firstName;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 500)
    @Column(name = "address1")
    private String address1;
    @Size(max = 500)
    @Column(name = "address2")
    private String address2;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "city")
    private String city;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "country")
    private String country;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 6)
    @Column(name = "postalCode")
    private String postalCode;
    @Size(max = 45)
    @Column(name = "homeTelephone")
    private String homeTelephone;
    @Size(max = 100)
    @Column(name = "companyName")
    private String companyName;
    @Size(max = 45)
    @Column(name = "cellTelephone")
    private String cellTelephone;
    // @Pattern(regexp="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", message="Invalid email")//if the field contains email address consider using this annotation to enforce field validation
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 320)
    @Column(name = "email")
    private String email;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 320)
    @Column(name = "password")
    private String password;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 320)
    @Column(name = "salt")
    private String salt;
    @Basic(optional = false)
    @NotNull
    @Column(name = "manager")
    private boolean manager;
    @JoinColumn(name = "provinceId", referencedColumnName = "id")
    @ManyToOne(optional = false)
    private Province provinceId;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "client")
    private List<Review> reviewList;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "clientId")
    private List<Order> OrderList;
    @OneToMany(mappedBy = "clientId")
    private List<SurveyClient> surveyClientList;

    public Client() {
    }

    public Client(Integer id) {
        this.id = id;
    }

    public Client(Integer id, String lastName, String firstName, String address1, String city, String country, String postalCode, String email, String password, String salt, boolean manager) {
        this.id = id;
        this.lastName = lastName;
        this.firstName = firstName;
        this.address1 = address1;
        this.city = city;
        this.country = country;
        this.postalCode = postalCode;
        this.email = email;
        this.password = password;
        this.salt = salt;
        this.manager = manager;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getHomeTelephone() {
        return homeTelephone;
    }

    public void setHomeTelephone(String homeTelephone) {
        this.homeTelephone = homeTelephone;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getCellTelephone() {
        return cellTelephone;
    }

    public void setCellTelephone(String cellTelephone) {
        this.cellTelephone = cellTelephone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public boolean getManager() {
        return manager;
    }

    public void setManager(boolean manager) {
        this.manager = manager;
    }

    public Province getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(Province provinceId) {
        this.provinceId = provinceId;
    }

    public List<Review> getReviewList() {
        return reviewList;
    }

    public void setReviewList(List<Review> reviewList) {
        this.reviewList = reviewList;
    }

    public List<Order> getOrderList() {
        return OrderList;
    }

    public void setOrderList(List<Order> OrderList) {
        this.OrderList = OrderList;
    }

    public List<SurveyClient> getSurveyClientList() {
        return surveyClientList;
    }

    public void setSurveyClientList(List<SurveyClient> surveyClientList) {
        this.surveyClientList = surveyClientList;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Client)) {
            return false;
        }
        Client other = (Client) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.ga2w20.entities.Client[ id=" + id + " ]";
    }    
}

src/main/java/com/ga2w20/backingbeans/BookBackingBean.java
package com.ga2w20.backingbeans;

import com.ga2w20.entities.Author;
import com.ga2w20.entities.Book;
import com.ga2w20.entities.Review;
import com.ga2w20.exceptions.NonexistentEntityException;
import com.ga2w20.exceptions.RollbackFailureException;
import com.ga2w20.jpacontroller.BookJpaController;
import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.enterprise.context.RequestScoped;
import javax.faces.view.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * The BookBackingBean contains all additional functionality for books, and is
 * managed by a single book attribute.
 * 
 * @author Liam Harbec, Svitlana Myronova 
 */
@Named("bookBackingBean")
@RequestScoped
public class BookBackingBean {

    
    @Inject
    private BookJpaController bookJpaController;

    private Book book;
    
    private List<Author> authors;

    
    private final static Logger LOG = LoggerFactory.getLogger(BookBackingBean.class);

    /**
     * Gets the isbn of the current book
     * 
     * @return The isbn
     */
    public long getIsbn() {
        if(book == null)
            return -1;
        return book.getIsbn();
    }
    
    
    /**
     * Sets the isbn of the current book
     * 
     * @param isbn The isbn to set
     */
    public void setIsbn(long isbn) {
        this.book = bookJpaController.findBook(isbn);
    }
    
    
    /**
     * Gets the book object, and creates a blank one if it does not already exist
     *
     * @return The fetched book
     */
    public Book getBook() {
        return this.book;
    }
    

    
    /**
     * Sets the current book object
     * 
     * @param book The book
     */
    public void setBook(Book book) {
        this.book = book;
    }
    
    
    /**
     * Fetches all of the authors of the current book
     * 
     * @return The authors of the book
     */
    public List<Author> getAuthors() {
        if (this.authors == null) {
            LOG.info("authors instantiated to the book's authors");
            this.authors = this.book.getAuthorList();
        }
        return this.authors;
    }
    
    
    /**
     * Calculates the average review rating of the book
     * 
     * @author Liam Harbec
     * @return The calculated book average
     */
    
    public int getAverageReview() {
        List<Review> reviews = getApprovedReviews();
        int total = 0;
        int reviewAmount = 0;
        for (Review r : reviews) {
            total += r.getRating();
            reviewAmount++;
        }
        return reviewAmount > 0 ? total/reviewAmount : total;
    }
    
    
    /**
     * Gets the genre of the current book object
     * 
     * @author Liam Harbec
     * @return The genre title
     */
    
    public String getGenre() {
        return this.book.getGenreId().getGenreTitle();
    }
    
    
    /**
     * Gets the publisher of the current book object
     * 
     * @author Liam Harbec
     * @return The publisher name
     */
    public String getPublisher() {
        return this.book.getPublisherId().getPublisherName();
    }
    
    
    /**
     * Gets similar books to the current book object.
     * 3 of these books are of the same genre.
     * At most 3 of these books are by the same author.
     * 
     * @author Liam Harbec
     * @return The similar books
     */
    
    public List<Book> getSimilarBooks() {
        String bookGenre = getGenre();
        String firstAuthor = getAuthors().get(0).getAuthorName();
        List<Book> booksWithGenre = this.bookJpaController.getBooksWithGenre(bookGenre, this.book.getIsbn());
        List<Book> booksWithAuthor = this.bookJpaController.getBooksWithAuthor(firstAuthor, this.book.getIsbn());
        
        ArrayList<Book> similarBooks = new ArrayList<>();
        
        // Removes the potential of duplicates
        Iterator<Book> itr = booksWithAuthor.iterator();
        while (itr.hasNext()) {
            Book bookByAuthor = itr.next();
            for (Book b : booksWithGenre) {
                if (bookByAuthor.equals(b)) {
                    itr.remove();
                }
            }
        }
        
        // Books by the same author
        if (booksWithAuthor.size() > 0) {
            // Maximum of 3 books per author
            if (booksWithAuthor.size() < 3) {
                for (int i = 0; i < booksWithAuthor.size(); i++) {
                    similarBooks.add(booksWithAuthor.get(i));
                }
            } else {
                for (int i = 0; i < 3; i++) {
                    similarBooks.add(booksWithAuthor.get(i));
                }
            }
        }
        
        // Books with the same genre
        for (int i = 0; similarBooks.size() < 6; i++) {
            similarBooks.add(booksWithGenre.get(i));
        }
        return similarBooks;
    }
    
    
    /**
     * Gets the price of a book with a sale price applied to it.
     * 
     * @author Liam Harbec
     * @return The price to be displayed
     */
    public String getBookSale() {
        BigDecimal percentageSale = calculateSalePercentage();
        if (percentageSale == BigDecimal.ZERO) {
            return null;
        } else {
            BigDecimal percent = percentageSale.divide(BigDecimal.valueOf(100));
            percent = BigDecimal.valueOf(1).subtract(percent);
            BigDecimal calculated = this.book.getListPrice().multiply(percent);
            calculated = calculated.setScale(2, RoundingMode.HALF_EVEN);
            return calculated + "";
        }
    }
    
    
    /**
     * Gets the sale percentage as a whole number
     * 
     * @author Liam Harbec
     * @return The percentage sale as a whole number
     */
    public BigDecimal getSalePercent() {
        BigDecimal percent = calculateSalePercentage();
        percent = percent.setScale(0, RoundingMode.DOWN);
        return percent;
    }
    
    
    /**
     * Gets the sale percentage of the current book object
     * 
     * @author Liam Harbec
     * @return The sale percentage
     */
    public BigDecimal calculateSalePercentage() {
        return bookJpaController.getSpecialBook(book.getIsbn(), new Date());
    }
    
    
    /**
     * Gets all reviews that have been approved by a manager. If the review has
     * not been approved, it will not be returned.
     * 
     * @author Liam Harbec
     * @return The reviews that have been approved
     */
    public List<Review> getApprovedReviews() {
        ArrayList<Review> list = new ArrayList<>();
        for (Review r : book.getReviewList()) {
            if (r.getApproved()) {
                list.add(r);
            }
        }
        return list;
    }
    
    /**
     * Method writes the LastGenreIdCookie cookie
     * 
     * @author Svitlana Myronova
     */
    public void writeCookie() {
        FacesContext context = FacesContext.getCurrentInstance();
        context.getExternalContext().addResponseCookie("LastGenreIdCookie", this.book.getGenreId().getId().toString(), null);
    }
}

src/main/webapp/WEB-INF/client/pages/404page.xhtml
<!-- Author: Liam Harbec -->

<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui" 
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <hr class="mx-5 mt-5"/>
    <div class="text-left my-5">
        <h1 class="ml-5">#{msg.Error_404}</h1>
        <h6 class="ml-5">#{msg.Error_Occurred}</h6>
    </div>
    
    <hr class="mx-5"/>
    
    <h4 class="mt-5" style="color: gray;">
        #{msg.Error_NotFound}
    </h4>
    <h6 class="mt-3" style="color: gray;">
        #{msg.Error_ReturnHome}
    </h6>
    
</ui:composition>

src/main/webapp/WEB-INF/client/pages/bookpage.xhtml
<!-- Author: Liam Harbec -->

<!-- Note: As XML does not support &nbsp, I had to use the hexadecimal notation of (&#160;) in certain places instead-->
<!--Sourced from: https://stackoverflow.com/questions/13012327/error-parsing-page-xhtml-error-tracedline-42-the-entity-nbsp-was-referenc -->
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui" 
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <ui:fragment rendered="#{bookBackingBean.book != null}">
        <!-- Image and relevant book info -->
        <div class="row mt-4">
            <div class="col ml-5 mt-3 mr-3">
                <p:graphicImage value="/#{bookBackingBean.book.imageFile}" styleClass="content" width="265px" height="400px"/>
            </div>
            <div class="col text-justify mr-3">
                <h4>#{bookBackingBean.book.title}</h4>

                <p:rating value="#{bookBackingBean.getAverageReview()}" readonly="true"/>

                <h:outputText value="#{msg.Book_By} "/>
                <!-- Loops through authors -->
                <ui:repeat var="author" value="#{bookBackingBean.book.authorList}" varStatus="status">
                    <h:outputText rendered="#{status.index+1 lt bookBackingBean.authors.size()}" value="#{author.authorName}, "/>
                    <h:outputText rendered="#{status.index+1 eq bookBackingBean.authors.size()}" value="#{author.authorName} "/>
                </ui:repeat>

                <h:outputText value="("/>
                <h:outputText value="#{bookBackingBean.book.publicationDate}">
                    <f:convertDateTime pattern="MMM dd, yyyy" />
                </h:outputText>
                <h:outputText value=")"/>

                <hr/>
                <p>#{bookBackingBean.book.description}</p>
                <hr/>
                <br/>
                <div class="text-center">
                    <div class="col">
                        <form>
                            <div class="col">
                                <div class="border mb-2 list-price px-2">
                                    <h:outputText value="#{msg.Book_ListPrice} "/>
                                    <!-- Regular price displayed -->
                                    <h:outputText
                                        value="$#{bookBackingBean.book.listPrice}"
                                        rendered="#{bookBackingBean.book.listPrice gt 0 and bookBackingBean.bookSale == null}"/>

                                    <!-- Book that is on sale -->
                                    <h:outputText
                                        value="$#{bookBackingBean.book.listPrice}"
                                        style="text-decoration: line-through;"
                                        rendered="#{bookBackingBean.bookSale != null and bookBackingBean.book.listPrice gt 0}"/>
                                    <h:outputText 
                                        value="  $#{bookBackingBean.bookSale} (#{bookBackingBean.salePercent}%)"
                                        style="color: red;"
                                        rendered="#{bookBackingBean.bookSale != null and bookBackingBean.book.listPrice gt 0}"/>

                                    <!-- Free book -->
                                    <!-- Was not working with 0, had to use a number less than 0.01 but greater than 0 -->
                                    <h:outputText value="#{msg.Book_Free}" rendered="#{bookBackingBean.book.listPrice lt 0.0000000001}"/>
                                </div>

                                <h:selectOneMenu>
                                    <h:outputText value="#{msg.Book_Format}: "/>
                                    <f:selectItems var="format"
                                                   value="#{bookBackingBean.book.formatList}"
                                                   itemLabel="#{format.formatTitle}"
                                                   itemValue="#{format}"/>
                                </h:selectOneMenu>
                            </div>
                            <br/>
                            <button type="submit" class="btn btn-primary btn-lg btn-block">#{msg.Book_AddToCart}</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <hr/>

        <!-- Additional book info -->
        <div class="row mt-4 ml-4">
            <div class="col text-left">
                <h5>#{msg.Book_BookDetails}</h5>
                #{msg.Book_Genre} 
                <h:outputText value="#{bookBackingBean.genre}"/><br/>
                #{msg.Book_Pages} 
                #{bookBackingBean.book.numberOfPages}<br/>
                #{msg.Book_Publisher}
                <h:outputText value="#{bookBackingBean.publisher}"/><br/>
                #{msg.Book_ISBN}
                #{bookBackingBean.book.isbn}<br/>
            </div>
        </div>

        <hr/>

        <!-- Books by same author or genre -->
        <h4>#{msg.Book_Similar}</h4>
        <div class="row mb-2 spaced">
            <ui:repeat var="book" value="#{bookBackingBean.similarBooks}">
                <div class="col">
                    <a href="book.xhtml?isbn=#{book.isbn}">
                        <p:graphicImage value="/#{book.imageFile}" styleClass="content" width="106px" height="160px"/>
                    </a>
                    <div class="row">
                        <a class="text-break text-wrap book-title mx-3" href="book.xhtml?isbn=#{book.isbn}">#{book.title}</a>
                    </div>
                </div>
            </ui:repeat>
        </div>

        <hr/>

        <!-- Reviews of the book -->
        <h4>#{msg.Book_CustomerReviews}</h4>
        <h:outputLink class="text-break text-wrap text-left"
                      value="#{sessionBackingBean.leaveReviewRedirect(bookBackingBean.book.isbn)}"
                      target="_blank">#{msg.Book_LeaveReview}</h:outputLink>
        <div class="col">
            <ui:repeat var="review" value="#{bookBackingBean.approvedReviews}">
                <div class="col text-left">
                    <div class="row">
                        <strong>#{review.client.firstName} #{review.client.lastName}</strong>&#160;
                        <h:outputText value="("/>
                        <h:outputText value="#{review.reviewDate}">
                            <f:convertDateTime pattern="MMM dd, yyyy" />
                        </h:outputText>
                        <h:outputText value=")"/>
                    </div>
                    <div class="row">
                        <p:rating value="#{review.rating}" readonly="true" />
                    </div>
                    <div>#{review.reviewText}</div>
                </div><br/><br/>
            </ui:repeat>
        </div>
        <br/>
        <h:outputText rendered="#{bookBackingBean.approvedReviews.size() eq 0}" value="#{msg.Book_NoReviews}"/>
        <br/><br/>
    </ui:fragment>
</ui:composition>

src/main/webapp/WEB-INF/client/pages/booksofgenrepage.xhtml
<!-- Author: Svitlana Myronova -->

<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui" 
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <h:form> 
        <!--The chosen genre-->    
        <h1 class="center my-4">
            <ui:fragment rendered="#{booksOfGenreBackingBean.genreTitle == null}"> 
                #{msg.BooksOfGenre_AllGenres}
            </ui:fragment>
            <ui:fragment rendered="#{booksOfGenreBackingBean.genreTitle != null}">
                #{booksOfGenreBackingBean.genreTitle}
            </ui:fragment>
        </h1>

        <!--Top Sellers of the chosen genre-->    
        <h2 class="center my-4">#{msg.BooksOfGenre_TopSellers}</h2>

        <div class="container-fluid">
            <div class="row justify-content-center">
                <ui:repeat value="#{booksOfGenreBackingBean.bestSellers}" var="bestSeller" > 
                    <div class= "col-auto my-3">
                        <div class="card" style="width:11rem;">
                            <h:link style="color: black;" outcome="book">
                                <f:param name="isbn" value="#{bestSeller.isbn}"/>
                                <img src="#{bestSeller.imageFile}" alt="#{bestSeller.title}" class="img-fluid"/>
                                <p>#{bestSeller.title}</p>
                                <ui:fragment rendered="#{bestSeller.salePrice.doubleValue()>0.0001}">   
                                    <p>
                                        <h:outputText value="#{bestSeller.salePrice}" style="font-weight: bold; color: red;">
                                            <f:convertNumber type="number" maxFractionDigits="2" />  
                                            <f:convertNumber currencySymbol = "CDN$" type = "currency" />
                                        </h:outputText>
                                    </p>
                                </ui:fragment>
                                <p>
                                    <h:outputText value="#{bestSeller.listPrice}" style="font-weight: bold; #{bestSeller.salePrice.doubleValue()>0.0001 ? 'text-decoration: line-through;' : ''}} ">
                                        <f:convertNumber type="number" maxFractionDigits="2" />  
                                        <f:convertNumber currencySymbol = "CDN$" type = "currency" />
                                    </h:outputText>
                                </p>
                            </h:link>
                        </div>
                    </div>
                </ui:repeat>
            </div>
        </div>

        <!--Books of a chosen genre-->    
        <h2 class="center my-4">#{msg.BooksOfGenre_Books}</h2>

        <ui:fragment rendered="#{booksOfGenreBackingBean.paginator.pagesTotal != 0}">
            <div class="my-5">
                <h:commandButton value="&lt; prev" action="#{booksOfGenreBackingBean.paginator.prev()}" class="btn btn-secondary" />
                <h:outputText value="#{booksOfGenreBackingBean.paginator.pageIndex} / #{booksOfGenreBackingBean.paginator.pagesTotal}" style="font-weight: bold;" class="px-3" />
                <h:commandButton value="next &gt;" action="#{booksOfGenreBackingBean.paginator.next()}" class="btn btn-secondary" />
                <h:inputHidden value="#{booksOfGenreBackingBean.paginator.pageIndex}"/>
            </div>
        </ui:fragment>
        <div class="container-fluid">
            <div class="row justify-content-center">
                <ui:repeat value="#{booksOfGenreBackingBean.paginator.model}" var="book" > 
                    <div class= "col-auto my-3">
                        <div class="card" style="width:11rem;">
                            <h:link style="color: black;" outcome="book">
                                <f:param name="isbn" value="#{book.isbn}"/>
                                <img src="#{book.imageFile}" alt="#{book.title}" class="img-fluid"/>
                                <p>#{book.title}</p>
                                <ui:fragment rendered="#{book.salePrice.doubleValue()>0.0001}">   
                                    <p>
                                        <h:outputText value="#{book.salePrice}" style="font-weight: bold; color: red;">
                                            <f:convertNumber type="number" maxFractionDigits="2" />  
                                            <f:convertNumber currencySymbol = "CDN$" type = "currency" />
                                        </h:outputText>
                                    </p>
                                </ui:fragment>
                                <p>
                                    <h:outputText value="#{book.listPrice}" style="font-weight: bold; #{book.salePrice.doubleValue()>0.0001 ? 'text-decoration: line-through;' : ''}} ">
                                        <f:convertNumber type="number" maxFractionDigits="2" />  
                                        <f:convertNumber currencySymbol = "CDN$" type = "currency" />
                                    </h:outputText>
                                </p>
                            </h:link>
                        </div>
                    </div>
                </ui:repeat>
            </div>
        </div>
        <ui:fragment rendered="#{booksOfGenreBackingBean.paginator.pagesTotal != 0}">
            <div class="my-5">
                <h:commandButton value="&lt; prev" action="#{booksOfGenreBackingBean.paginator.prev()}" class="btn btn-secondary" />
                <h:outputText value="#{booksOfGenreBackingBean.paginator.pageIndex} / #{booksOfGenreBackingBean.paginator.pagesTotal}" style="font-weight: bold;" class="px-3" />
                <h:commandButton value="next &gt;" action="#{booksOfGenreBackingBean.paginator.next()}" class="btn btn-secondary" />
                <h:inputHidden value="#{booksOfGenreBackingBean.paginator.pageIndex}"/>
            </div>
        </ui:fragment>
    </h:form>
</ui:composition>